### ISSUE TITLE
Alpha value is not preserved when set with rgba, and getting rgba and hsva returns undefined for opaque colors

### ISSUE THREAD

**Issue by DeveloperBlue** [jaames/iro-transparency-plugin#2]
Iro: 4.2.2
Transparency plugin: 1.0.1
Chrome: Version 73.0.3683.86 [On Windows 7]

If you pass an _rgbaString_ to `iro.Color()`, and then get an _rgbaString_ or _hsva_ object, it throws away the alpha value and sets it to 0. This is unexpected behavior as one would want the alpha be preserved if given, and returned appropriately.

Also, if you attempt to get an _rgb**a**String_ or _hsv**a**_ object after setting `iro.Color()` with a color that does not have an alpha, like `#fff` or `rgb(255, 0, 120)`, the alpha is returned as `undefined`. I would argue it makes more sense to return the alpha as 1, to represent that it is a solid opaque color.

You can observe this here:
```javascript
iro.use(iroTransparencyPlugin);

var temporaryColorObject = new iro.Color();

function testColor(colorReference){
	temporaryColorObject.set(colorReference);
	console.log(colorReference, "-->", temporaryColorObject["rgbaString"]);
	console.log(colorReference, "-->", temporaryColorObject["hsva"]);
}

testColor("#fff");
testColor("rgb(255, 102, 0)");
testColor("rgba(255, 102, 0, 0.55)");
testColor({h: 360, s: 240, v: 25});
testColor({h: 360, s: 120, v: 50, a: 0.2});
```

**Comment by jaames** [comment]
Thanks for opening another issue thread for this :)

Part of the problem was within iro.js itself, so using version 4.3.1 should fix instances where the alpha was `undefined` after setting `iro.Color` to a color that lacks an alpha component.

I'll also need to change some things within this plugin too.

**Comment by jaames** [comment]
@DeveloperBlue please go ahead and try updating to iro.js 4.3.1 and iro-transparency-plugin 1.0.2, hopefully everything should be fixed now! Also do feel free to reopen this thread or open another one if you experience any other issues.

**Comment by sjaakp** [comment]
I'm afraid this issue is still very much alive. 

Basically, I can't set color to something like 'rgba(0, 0, 255, 0.5)'. Alpha will be interpreted as 0. Setting color to 'rgba(0, 0, 255, .5)' does work correctly.

Using iro.js 4.3.1 and iro-transparency-plugin 1.0.2.

Excellent color picker though; I really like the minimalist looks.

**Comment by jaames** [comment]
You're right @sjaakp, while this is technically seperate to the previous issue, it looks like the regex that iro.js was using to parse rgba and hsla color strings wasn't handling decimal numbers correctly. It should try parsing values as a decimal `CSS_NUMBER` first, then fall back to `CSS_INTEGER` if there is no decimal place.

I've just fixed pushed a fix for this with iro.js v4.3.3, so please make sure to update. :)

Also thank you for the kind words, glad you like the library!

----

Sidenote: this regex issue somehow managed to slip through my code tests, so I've also updated them to mitigate any further issues with this.
